(package "com-css-sort"
         "0.0.7"
         "Common way of sorting the CSS attributes")

(website-url "https://github.com/jcs-elpa/com-css-sort")
(keywords "Common" "CSS" "Handy" "Sort" "Sorting")

(package-file "com-css-sort.el")

(source "melpa")

(depends-on "emacs" "25.1")
(depends-on "s")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
